export interface UseCase {
  slug: string
  title: string
  description: string
  icon: string
  skills: {
    slug: string
    name: string
    reason: string
  }[]
  searchLink?: string
}

export const USE_CASES: UseCase[] = [
  // ── WORK ──────────────────────────────────────────────
  {
    slug: 'weekly-report',
    title: 'Write Weekly Reports',
    description: 'Generate professional weekly, daily, and monthly reports automatically — save 2+ hours every week.',
    icon: '📝',
    skills: [
      { slug: 'report-generator', name: 'Report Generator', reason: 'Auto-generate structured weekly/monthly reports' },
      { slug: 'note-taker', name: 'Note Taker', reason: 'Capture daily work logs to feed into reports' },
      { slug: 'excel-formula', name: 'Excel Formula', reason: 'Build data tables and charts for your reports' },
      { slug: 'story-writer', name: 'Story Writer', reason: 'Polish report language for executive audiences' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Track completed tasks to include in your summary' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Set automated reminders for report deadlines' },
    ],
    searchLink: '/skills?q=report+generator+weekly',
  },
  {
    slug: 'build-saas',
    title: 'Build a SaaS Product',
    description: 'The essential AI skill stack for indie hackers and small teams shipping a SaaS product — from architecture to deployment.',
    icon: '🚀',
    skills: [
      { slug: 'code-generator', name: 'Code Generator', reason: 'Generate boilerplate, API routes, and components instantly' },
      { slug: 'database-design', name: 'Database Design', reason: 'Schema design, migrations, and query optimization' },
      { slug: 'api-generator', name: 'API Generator', reason: 'REST and GraphQL API scaffolding in seconds' },
      { slug: 'debugger', name: 'Debugger', reason: 'Trace errors and fix issues across your stack' },
      { slug: 'geo-seo', name: 'GEO SEO', reason: 'Get your SaaS discovered by AI search engines from day one' },
    ],
  },
  {
    slug: 'developer-workflow',
    title: 'Developer Daily Workflow',
    description: 'The skills that make your dev environment smarter — from writing code to shipping and monitoring.',
    icon: '⚡',
    skills: [
      { slug: 'shell', name: 'Shell Toolkit', reason: 'Master CLI operations and automate repetitive tasks' },
      { slug: 'debugger', name: 'Debugger', reason: 'Root cause analysis for any error or stack trace' },
      { slug: 'database-design', name: 'Database Design', reason: 'Design schemas and write optimized queries' },
      { slug: 'api-generator', name: 'API Generator', reason: 'Generate API specs and client code instantly' },
      { slug: 'code-generator', name: 'Code Generator', reason: 'Stop writing boilerplate, start writing logic' },
    ],
  },
  {
    slug: 'job-hunting',
    title: 'Job Hunting & Career',
    description: 'Land your next role faster with AI skills that help you craft applications, prep for interviews, and negotiate offers.',
    icon: '💼',
    skills: [
      { slug: 'task-planner', name: 'Task Planner', reason: 'Organize your job search pipeline and follow-ups' },
      { slug: 'story-writer', name: 'Story Writer', reason: 'Write compelling cover letters and personal statements' },
      { slug: 'legal-advisor', name: 'Legal Advisor', reason: 'Understand employment contracts and negotiate terms' },
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Apply to international roles with localized materials' },
    ],
  },
  {
    slug: 'remote-work',
    title: 'Remote Work Productivity',
    description: 'Stay focused and organized working from anywhere — AI tools for async communication, task tracking, and deep work.',
    icon: '🏠',
    skills: [
      { slug: 'task-planner', name: 'Task Planner', reason: 'Manage tasks and priorities across time zones' },
      { slug: 'note-taker', name: 'Note Taker', reason: 'Capture meeting notes and action items automatically' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Block deep work sessions and manage your calendar' },
      { slug: 'story-writer', name: 'Story Writer', reason: 'Write clear async updates and documentation' },
    ],
  },
  {
    slug: 'startup-founder',
    title: 'Startup Founder Toolkit',
    description: 'From idea to funding — AI skills to help founders move fast, pitch confidently, and build lean.',
    icon: '🦄',
    skills: [
      { slug: 'business-plan', name: 'Business Plan', reason: 'Structure your pitch deck and business model' },
      { slug: 'legal-advisor', name: 'Legal Advisor', reason: 'Draft founder agreements, NDAs, and term sheets' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Build metrics dashboards and investor reports' },
      { slug: 'geo-seo', name: 'GEO SEO', reason: 'Get found by early adopters through AI search' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Manage your roadmap and team priorities' },
    ],
  },
  {
    slug: 'project-manager',
    title: 'Project Management',
    description: 'Deliver projects on time with AI skills for planning, tracking, reporting, and stakeholder communication.',
    icon: '📋',
    skills: [
      { slug: 'task-planner', name: 'Task Planner', reason: 'Break down projects into trackable milestones' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Build timelines and spot scheduling conflicts early' },
      { slug: 'note-taker', name: 'Note Taker', reason: 'Capture meeting decisions and distribute action items' },
      { slug: 'excel-formula', name: 'Excel Formula', reason: 'Build project trackers and budget spreadsheets' },
    ],
  },
  {
    slug: 'hr-recruiting',
    title: 'HR & Recruiting',
    description: 'Hire better and faster — AI skills for writing job posts, screening candidates, and onboarding new hires.',
    icon: '🧑‍💼',
    skills: [
      { slug: 'hr-toolkit', name: 'HR Toolkit', reason: 'Draft JDs, offer letters, and onboarding plans' },
      { slug: 'interview-analysis', name: 'Interview Analysis', reason: 'Evaluate candidates with structured frameworks' },
      { slug: 'legal-advisor', name: 'Legal Advisor', reason: 'Stay compliant with labor laws and contracts' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Track pipeline stages and hiring deadlines' },
    ],
  },

  // ── CREATE ─────────────────────────────────────────────
  {
    slug: 'content-creator',
    title: 'Content Creator Toolkit',
    description: 'AI skills for YouTubers, bloggers, and social media creators who want to produce more content with less effort.',
    icon: '🎬',
    skills: [
      { slug: 'story-writer', name: 'Story Writer', reason: 'Craft engaging narratives and scripts for any format' },
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Reach global audiences with accurate translations' },
      { slug: 'shell', name: 'Shell Toolkit', reason: 'Automate file renaming, batch processing, and uploads' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Plan your content calendar and publishing schedule' },
    ],
  },
  {
    slug: 'video-creator',
    title: 'Video Creator & YouTuber',
    description: 'From script to upload — AI skills to speed up video production, optimize titles, and grow your channel.',
    icon: '📹',
    skills: [
      { slug: 'short-drama-writer', name: 'Script Writer', reason: 'Write engaging video scripts with hooks and pacing' },
      { slug: 'bilibili-helper', name: 'Video Optimizer', reason: 'Optimize titles, tags, and thumbnails for discovery' },
      { slug: 'story-writer', name: 'Story Writer', reason: 'Build narrative arcs for longer-form content' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Manage your filming and editing schedule' },
    ],
  },
  {
    slug: 'writer-author',
    title: 'Writer & Author',
    description: 'Write faster and better — AI skills for novelists, bloggers, journalists, and copywriters.',
    icon: '✍️',
    skills: [
      { slug: 'story-writer', name: 'Story Writer', reason: 'Develop characters, plot, and world-building' },
      { slug: 'note-taker', name: 'Note Taker', reason: 'Capture research and organize ideas with Zettelkasten' },
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Translate your work into multiple languages' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Hit writing goals with daily word count tracking' },
    ],
  },
  {
    slug: 'marketing-automation',
    title: 'Marketing Automation',
    description: 'Scale your marketing efforts with AI skills for content, email, analytics, and campaign management.',
    icon: '📣',
    skills: [
      { slug: 'story-writer', name: 'Story Writer', reason: 'Generate ad copy, email sequences, and blog posts' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Manage campaigns, deadlines, and team tasks' },
      { slug: 'geo-seo', name: 'GEO SEO', reason: 'Get your brand mentioned in AI-generated answers' },
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Localize campaigns for international markets' },
    ],
  },
  {
    slug: 'seo-geo',
    title: 'SEO & GEO Optimization',
    description: 'Optimize your website for both traditional search engines and the new generation of AI-powered search.',
    icon: '🔍',
    skills: [
      { slug: 'geo-seo', name: 'GEO SEO', reason: 'Complete guide to getting cited by ChatGPT, Perplexity, and Gemini' },
      { slug: 'legal-advisor', name: 'Legal Advisor', reason: 'Draft compliant privacy policies and terms of service' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Plan your content and link-building roadmap' },
    ],
  },
  {
    slug: 'podcast-creator',
    title: 'Podcast Producer',
    description: 'Plan, record, and grow your podcast — AI skills for show notes, guest research, and audience building.',
    icon: '🎙️',
    skills: [
      { slug: 'note-taker', name: 'Note Taker', reason: 'Organize research notes for each episode' },
      { slug: 'story-writer', name: 'Story Writer', reason: 'Write show notes, episode summaries, and descriptions' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Manage guest outreach and release schedule' },
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Reach global listeners with translated transcripts' },
    ],
  },

  // ── LEARN ──────────────────────────────────────────────
  {
    slug: 'learn-programming',
    title: 'Learn Programming',
    description: 'Accelerate your coding journey with AI skills that explain concepts, debug your code, and guide your learning path.',
    icon: '📚',
    skills: [
      { slug: 'code-generator', name: 'Code Generator', reason: 'See working examples for any concept you\'re learning' },
      { slug: 'debugger', name: 'Debugger', reason: 'Understand why your code breaks and how to fix it' },
      { slug: 'shell', name: 'Shell Toolkit', reason: 'Get comfortable with the terminal from day one' },
      { slug: 'database-design', name: 'Database Design', reason: 'Learn SQL and data modeling with real examples' },
    ],
  },
  {
    slug: 'language-learner',
    title: 'Language Learning',
    description: 'Pick up a new language faster with AI skills for translation, writing practice, and vocabulary building.',
    icon: '🌍',
    skills: [
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Instant translation with context and nuance explanations' },
      { slug: 'story-writer', name: 'Story Writer', reason: 'Practice writing in your target language with feedback' },
      { slug: 'note-taker', name: 'Note Taker', reason: 'Build your vocabulary notebook and review system' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Schedule daily practice sessions and track streaks' },
    ],
  },
  {
    slug: 'student',
    title: 'Student & Academic',
    description: 'Study smarter, write better papers, and manage deadlines with AI skills built for academic life.',
    icon: '🎓',
    skills: [
      { slug: 'note-taker', name: 'Note Taker', reason: 'Cornell notes, Zettelkasten, and lecture summaries' },
      { slug: 'math-solver', name: 'Math Solver', reason: 'Step-by-step solutions for calculus, stats, and more' },
      { slug: 'story-writer', name: 'Essay Writer', reason: 'Structure arguments and polish academic writing' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Manage deadlines, exams, and group projects' },
    ],
  },
  {
    slug: 'researcher',
    title: 'Researcher & Analyst',
    description: 'Synthesize information, build reports, and present findings with AI-powered research skills.',
    icon: '🔬',
    skills: [
      { slug: 'note-taker', name: 'Note Taker', reason: 'Organize literature reviews with Zettelkasten method' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Run statistical analysis and visualize findings' },
      { slug: 'story-writer', name: 'Report Writer', reason: 'Structure and write clear research reports' },
      { slug: 'mindmap', name: 'Mind Map', reason: 'Visualize complex relationships and frameworks' },
    ],
  },

  // ── INVEST ─────────────────────────────────────────────
  {
    slug: 'crypto-research',
    title: 'Crypto & DeFi Research',
    description: 'Research protocols, track markets, and analyze on-chain data with AI-powered crypto skills.',
    icon: '🪙',
    skills: [
      { slug: 'us-stock-analysis', name: 'Market Analysis', reason: 'Technical and fundamental analysis for crypto assets' },
      { slug: 'investment-portfolio', name: 'Portfolio Tracker', reason: 'Track your crypto holdings and P&L in real time' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Analyze on-chain metrics and market trends' },
      { slug: 'note-taker', name: 'Research Notes', reason: 'Build your investment thesis and track due diligence' },
    ],
  },
  {
    slug: 'stock-investor',
    title: 'Stock Market Investor',
    description: 'Research equities, analyze financials, and manage your portfolio with AI skills for serious investors.',
    icon: '📈',
    skills: [
      { slug: 'us-stock-analysis', name: 'US Stock Analysis', reason: 'Fundamental and technical analysis for any ticker' },
      { slug: 'fundamental-stock-analysis', name: 'Fundamental Analysis', reason: 'DCF, ratios, and quality scoring' },
      { slug: 'investment-portfolio', name: 'Portfolio Tracker', reason: 'Monitor allocation, returns, and risk exposure' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Build screeners and compare financial metrics' },
    ],
  },
  {
    slug: 'data-analysis',
    title: 'Data Analysis',
    description: 'Extract insights from data using AI skills for visualization, statistics, and pipeline automation.',
    icon: '📊',
    skills: [
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Query databases, generate reports, turn data into insights' },
      { slug: 'excel-formula', name: 'Excel Formula', reason: 'Write complex formulas and automate spreadsheet tasks' },
      { slug: 'data-visualizer', name: 'Data Visualizer', reason: 'Create charts and dashboards from CSV or JSON' },
      { slug: 'database-design', name: 'Database Design', reason: 'Query and transform datasets with optimized SQL' },
    ],
  },
  {
    slug: 'personal-finance',
    title: 'Personal Finance',
    description: 'Take control of your money — AI skills for budgeting, investment tracking, and financial planning.',
    icon: '💰',
    skills: [
      { slug: 'investment-portfolio', name: 'Portfolio Tracker', reason: 'Track all your investments in one place' },
      { slug: 'excel-formula', name: 'Excel Formula', reason: 'Build budget spreadsheets and expense trackers' },
      { slug: 'legal-advisor', name: 'Legal Advisor', reason: 'Understand financial contracts and tax obligations' },
      { slug: 'task-planner', name: 'Goal Planner', reason: 'Set savings goals and track your financial milestones' },
    ],
  },

  // ── LIFE ───────────────────────────────────────────────
  {
    slug: 'ecommerce',
    title: 'E-commerce Store',
    description: 'Run a smarter online store with AI skills for product descriptions, pricing, customer support, and analytics.',
    icon: '🛍️',
    skills: [
      { slug: 'story-writer', name: 'Story Writer', reason: 'Write compelling product descriptions that convert' },
      { slug: 'shopify-helper', name: 'Shopify Helper', reason: 'Set up and optimize your Shopify storefront' },
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Sell globally with localized product listings' },
      { slug: 'inventory-manager', name: 'Inventory Manager', reason: 'Track stock levels, SKUs, and reorder points' },
    ],
  },
  {
    slug: 'travel-planner',
    title: 'Travel Planning',
    description: 'Plan unforgettable trips with AI skills for itineraries, budgeting, language help, and local research.',
    icon: '✈️',
    skills: [
      { slug: 'task-planner', name: 'Trip Planner', reason: 'Build day-by-day itineraries with time estimates' },
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Communicate in any language on the road' },
      { slug: 'note-taker', name: 'Travel Notes', reason: 'Keep a travel journal and log recommendations' },
      { slug: 'excel-formula', name: 'Budget Tracker', reason: 'Track expenses and split costs with travel companions' },
    ],
  },
  {
    slug: 'health-fitness',
    title: 'Health & Fitness',
    description: 'Build sustainable healthy habits — AI skills for workout planning, nutrition tracking, and wellness goals.',
    icon: '💪',
    skills: [
      { slug: 'task-planner', name: 'Habit Tracker', reason: 'Build and track daily fitness routines' },
      { slug: 'scheduler', name: 'Workout Scheduler', reason: 'Plan training blocks and recovery days' },
      { slug: 'note-taker', name: 'Wellness Journal', reason: 'Log workouts, sleep, and nutrition for pattern spotting' },
      { slug: 'math-solver', name: 'Calorie Calculator', reason: 'Calculate macros, TDEE, and nutrition targets' },
    ],
  },
  {
    slug: 'home-cooking',
    title: 'Home Cooking & Recipes',
    description: 'Cook better meals at home — AI skills for recipe discovery, meal planning, and kitchen organization.',
    icon: '🍳',
    skills: [
      { slug: 'task-planner', name: 'Meal Planner', reason: 'Plan weekly menus and generate shopping lists' },
      { slug: 'note-taker', name: 'Recipe Notes', reason: 'Save and organize your favorite recipes' },
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Cook from foreign-language cookbooks with ease' },
      { slug: 'excel-formula', name: 'Grocery Budget', reason: 'Track grocery spending and reduce food waste' },
    ],
  },
  {
    slug: 'smart-home',
    title: 'Smart Home & Automation',
    description: 'Automate your home life with AI skills for device control, routines, and energy management.',
    icon: '🏡',
    skills: [
      { slug: 'shell', name: 'Shell Toolkit', reason: 'Write automation scripts for home systems' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Set up time-based routines and triggers' },
      { slug: 'task-planner', name: 'Home Planner', reason: 'Manage maintenance tasks and home improvement projects' },
      { slug: 'note-taker', name: 'Home Notes', reason: 'Keep appliance manuals, warranty info, and repair logs' },
    ],
  },
  {
    slug: 'legal-documents',
    title: 'Legal Documents & Compliance',
    description: 'Understand and create legal documents without a lawyer — contracts, policies, and compliance checklists.',
    icon: '⚖️',
    skills: [
      { slug: 'legal-advisor', name: 'Legal Advisor', reason: 'Draft and review contracts, NDAs, and agreements' },
      { slug: 'story-writer', name: 'Document Writer', reason: 'Write clear policies and compliance documentation' },
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Translate legal documents for international use' },
      { slug: 'task-planner', name: 'Compliance Tracker', reason: 'Track regulatory deadlines and audit requirements' },
    ],
  },

  // ── NEW: HackerNews-validated high-demand use cases ──
  {
    slug: 'crm-sales',
    title: 'CRM & Sales Management',
    description: 'Let your AI agent manage leads, track deals, and automate follow-ups — no more manual CRM updates.',
    icon: '💼',
    skills: [
      { slug: 'crm-manager', name: 'CRM Manager', reason: 'Create contacts, update deals, and log notes automatically' },
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Draft follow-up emails and outreach sequences' },
      { slug: 'task-planner', name: 'Pipeline Tracker', reason: 'Track deals through stages and set follow-up reminders' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Analyze win rates, pipeline velocity, and revenue forecasts' },
      { slug: 'scheduler', name: 'Meeting Scheduler', reason: 'Book demos and sync calendars without back-and-forth' },
      { slug: 'note-taker', name: 'Call Notes', reason: 'Capture meeting notes and extract action items instantly' },
    ],
    searchLink: '/skills?q=crm+sales+leads',
  },
  {
    slug: 'workflow-automation',
    title: 'Workflow Automation',
    description: 'Convert your n8n flows, Zapier zaps, and manual processes into AI agent skills that run automatically.',
    icon: '⚡',
    skills: [
      { slug: 'shell', name: 'Shell Toolkit', reason: 'Automate repetitive tasks with powerful scripts' },
      { slug: 'api-tester', name: 'API Connector', reason: 'Connect any service via REST API without code' },
      { slug: 'scheduler', name: 'Cron Scheduler', reason: 'Trigger workflows on time or on event' },
      { slug: 'task-planner', name: 'Workflow Planner', reason: 'Map out and optimize your automation pipelines' },
      { slug: 'note-taker', name: 'Run Logger', reason: 'Track automation runs and catch failures early' },
      { slug: 'excel-formula', name: 'Data Transformer', reason: 'Clean and transform data between workflow steps' },
    ],
    searchLink: '/skills?q=automation+workflow+n8n',
  },
  {
    slug: 'customer-support',
    title: 'Customer Support Automation',
    description: 'Handle support tickets, auto-reply to common questions, and escalate edge cases — 24/7 without a team.',
    icon: '🎧',
    skills: [
      { slug: 'email-assistant', name: 'Email Responder', reason: 'Auto-reply to common support requests with accurate answers' },
      { slug: 'story-writer', name: 'FAQ Writer', reason: 'Build a knowledge base from past tickets' },
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Support customers in multiple languages automatically' },
      { slug: 'task-planner', name: 'Ticket Tracker', reason: 'Route and prioritize tickets by urgency' },
      { slug: 'note-taker', name: 'Interaction Logger', reason: 'Log every customer interaction for quality review' },
      { slug: 'data-analysis', name: 'Support Analytics', reason: 'Track resolution time, CSAT, and ticket trends' },
    ],
    searchLink: '/skills?q=customer+support+helpdesk',
  },
  {
    slug: 'database-management',
    title: 'Database & Data Management',
    description: 'Query, migrate, and manage databases with AI — SQL generation, schema design, and data pipeline automation.',
    icon: '🗄️',
    skills: [
      { slug: 'sql-assistant', name: 'SQL Assistant', reason: 'Generate complex queries from plain English descriptions' },
      { slug: 'excel-formula', name: 'Data Processor', reason: 'Transform and clean datasets before loading' },
      { slug: 'shell', name: 'DB Scripts', reason: 'Automate backups, migrations, and maintenance tasks' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Visualize query results and spot anomalies' },
      { slug: 'api-tester', name: 'API Tester', reason: 'Test and validate database API endpoints' },
      { slug: 'note-taker', name: 'Schema Docs', reason: 'Auto-generate database documentation from schema' },
    ],
    searchLink: '/skills?q=database+sql+data',
  },
  {
    slug: 'security-audit',
    title: 'Security & Code Audit',
    description: 'Review AI agent skills, code, and configs for security risks — catch vulnerabilities before they become incidents.',
    icon: '🔒',
    skills: [
      { slug: 'code-reviewer', name: 'Code Reviewer', reason: 'Scan code for common security vulnerabilities' },
      { slug: 'shell', name: 'Security Scanner', reason: 'Run automated security checks and penetration tests' },
      { slug: 'api-tester', name: 'API Security Tester', reason: 'Test endpoints for auth issues and data leaks' },
      { slug: 'note-taker', name: 'Audit Logger', reason: 'Document findings and track remediation progress' },
      { slug: 'task-planner', name: 'Risk Tracker', reason: 'Prioritize vulnerabilities by severity and impact' },
      { slug: 'story-writer', name: 'Security Report', reason: 'Generate executive-ready security audit reports' },
    ],
    searchLink: '/skills?q=security+audit+vulnerability',
  },

  // ── DATA-DRIVEN: tag gap analysis (writing/data/seo/ecommerce/translation/health) ──
  {
    slug: 'content-writing',
    title: 'Content Writing & Copywriting',
    description: 'Write faster and better — AI skills for blog posts, ad copy, social captions, product descriptions, and long-form content.',
    icon: '✍️',
    skills: [
      { slug: 'story-writer', name: 'Story Writer', reason: 'Craft engaging long-form articles and narratives' },
      { slug: 'humanizer', name: 'Humanizer', reason: 'Make AI-generated text sound natural and authentic' },
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Adapt content for global audiences instantly' },
      { slug: 'email-assistant', name: 'Email Copywriter', reason: 'Write high-converting email sequences and newsletters' },
      { slug: 'note-taker', name: 'Idea Capture', reason: 'Never lose a content idea — capture and organize instantly' },
      { slug: 'task-planner', name: 'Content Calendar', reason: 'Plan and schedule your publishing pipeline' },
    ],
    searchLink: '/skills?q=writing+copywriting+content',
  },
  {
    slug: 'data-analysis',
    title: 'Data Analysis & Visualization',
    description: 'Turn raw data into clear insights — AI skills for querying, cleaning, visualizing, and reporting on any dataset.',
    icon: '📊',
    skills: [
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Query databases, generate reports, and spot trends automatically' },
      { slug: 'excel-formula', name: 'Excel & Sheets', reason: 'Build formulas, pivot tables, and dashboards without googling' },
      { slug: 'chart-generator', name: 'Chart Generator', reason: 'Create beautiful charts from any data source' },
      { slug: 'sql-assistant', name: 'SQL Assistant', reason: 'Write complex queries from plain English descriptions' },
      { slug: 'data-analyst', name: 'Data Analyst Pro', reason: 'End-to-end analysis from raw files to executive summary' },
      { slug: 'shell', name: 'Data Pipeline', reason: 'Automate data cleaning, transformation, and loading' },
    ],
    searchLink: '/skills?q=data+analysis+visualization',
  },
  {
    slug: 'seo-growth',
    title: 'SEO & Organic Growth',
    description: 'Rank higher and grow traffic — AI skills for keyword research, content optimization, backlink strategy, and technical SEO.',
    icon: '🚀',
    skills: [
      { slug: 'geo-seo', name: 'GEO & SEO', reason: 'Optimize for both Google search and AI answer engines' },
      { slug: 'story-writer', name: 'SEO Content Writer', reason: 'Write keyword-optimized articles that actually rank' },
      { slug: 'multi-search-engine', name: 'Keyword Research', reason: 'Find low-competition keywords across 17 search engines' },
      { slug: 'data-analysis', name: 'Traffic Analytics', reason: 'Analyze GSC data and find ranking opportunities' },
      { slug: 'api-tester', name: 'Technical SEO Auditor', reason: 'Check site speed, canonicals, and crawlability issues' },
      { slug: 'task-planner', name: 'SEO Roadmap', reason: 'Prioritize and track SEO tasks by impact' },
    ],
    searchLink: '/skills?q=seo+keyword+traffic',
  },
  {
    slug: 'ecommerce-ops',
    title: 'E-commerce Operations',
    description: 'Run your online store on autopilot — AI skills for product listings, inventory, customer service, and ad optimization.',
    icon: '🛒',
    skills: [
      { slug: 'story-writer', name: 'Product Copywriter', reason: 'Write compelling product titles, descriptions, and bullet points' },
      { slug: 'email-assistant', name: 'Customer Email', reason: 'Handle order questions, returns, and follow-ups automatically' },
      { slug: 'data-analysis', name: 'Sales Analytics', reason: 'Track revenue, margins, and bestsellers in real time' },
      { slug: 'translator-pro', name: 'Listing Translator', reason: 'Sell globally — translate listings for any market' },
      { slug: 'task-planner', name: 'Inventory Planner', reason: 'Forecast stock needs and prevent out-of-stock' },
      { slug: 'shell', name: 'Price Monitor', reason: 'Track competitor prices and alert on changes automatically' },
    ],
    searchLink: '/skills?q=ecommerce+product+listing',
  },
  {
    slug: 'translation-localization',
    title: 'Translation & Localization',
    description: 'Break language barriers instantly — AI skills for translating documents, websites, subtitles, and multilingual content at scale.',
    icon: '🌐',
    skills: [
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Accurate translations across 100+ languages with context' },
      { slug: 'story-writer', name: 'Localization Writer', reason: 'Adapt content culturally, not just linguistically' },
      { slug: 'shell', name: 'Batch Translator', reason: 'Translate entire folders of files automatically' },
      { slug: 'note-taker', name: 'Glossary Manager', reason: 'Maintain consistent terminology across all translations' },
      { slug: 'api-tester', name: 'API Translator', reason: 'Connect to DeepL, Google Translate, or any translation API' },
      { slug: 'task-planner', name: 'Localization Tracker', reason: 'Track translation progress across languages and markets' },
    ],
    searchLink: '/skills?q=translation+localization',
  },
  {
    slug: 'health-wellness',
    title: 'Health & Wellness',
    description: 'Take charge of your health with AI — meal planning, workout tracking, symptom research, and wellness habit building.',
    icon: '💪',
    skills: [
      { slug: 'meal-planner', name: 'Meal Planner', reason: 'Generate personalized weekly meal plans and shopping lists' },
      { slug: 'fitness-tracker', name: 'Workout Builder', reason: 'Create custom exercise routines for your goals and schedule' },
      { slug: 'note-taker', name: 'Health Journal', reason: 'Log symptoms, moods, and habits to spot patterns' },
      { slug: 'data-analysis', name: 'Health Analytics', reason: 'Analyze your wearable data and track progress over time' },
      { slug: 'scheduler', name: 'Wellness Scheduler', reason: 'Build sustainable daily routines and stick to them' },
      { slug: 'story-writer', name: 'Medical Summarizer', reason: 'Summarize health articles and medical reports in plain English' },
    ],
    searchLink: '/skills?q=health+fitness+wellness',
  },


  // ── AUTO-GENERATED: 2026-04-02 ──
  {
    slug: 'grant-deadline-guardian',
    title: 'Never Miss Grant Deadlines',
    description: 'Monitors government and foundation grant portals, parses deadlines, and sends proactive alerts with application prep steps.',
    icon: '⏰',
    skills: [
      { slug: 'scheduler', name: 'Scheduler', reason: 'Schedules deadline checks and reminder triggers' },
      { slug: 'web-scraper', name: 'Web Scraper', reason: 'Extracts deadlines from CEIDG, KRS, EU Funding portals' },
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Drafts follow-up emails to grant officers' },
      { slug: 'note-taker', name: 'Note Taker', reason: 'Summarizes eligibility criteria and required docs' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Breaks down application into subtasks with due dates' },
    ],
    searchLink: '/skills?q=deadline+monitoring+grant+application+calendar',
  },
  {
    slug: 'incident-responder',
    title: 'Auto-Resolve DevOps Incidents',
    description: 'Analyzes alert logs, correlates errors across tools, executes runbook actions, and documents resolution in real time.',
    icon: '🚨',
    skills: [
      { slug: 'log-analyzer', name: 'Log Analyzer', reason: 'Parses CloudWatch, Datadog, or Loki error patterns' },
      { slug: 'shell', name: 'Shell', reason: 'Runs remediation scripts on Kubernetes or servers' },
      { slug: 'api-tester', name: 'API Tester', reason: 'Validates service health post-fix via API calls' },
      { slug: 'note-taker', name: 'Note Taker', reason: 'Generates post-mortem summaries for Slack/Confluence' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Triggers periodic health checks after incident closure' },
    ],
    searchLink: '/skills?q=devops+incident+response+pagerduty+prometheus',
  },
  {
    slug: 'airbnb-host-orchestrator',
    title: 'Automate Airbnb Guest Journeys',
    description: 'Manages end-to-end guest communication, dynamic pricing, cleaning coordination, and review requests across platforms.',
    icon: '🏡',
    skills: [
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Sends check-in instructions and local tips' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Books cleaners and coordinates key handoffs' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Recommends dynamic pricing based on demand and events' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Sequences pre-arrival, during-stay, and post-departure tasks' },
      { slug: 'review-collector', name: 'Review Collector', reason: 'Requests reviews via SMS/email at optimal timing' },
    ],
    searchLink: '/skills?q=airbnb+host+automation+pricing+cleaning+reviews',
  },
  {
    slug: 'video-clipping-director',
    title: 'Turn Long Videos Into Shorts',
    description: 'Watches long-form content, identifies high-engagement moments, clips them, adds captions and hooks, then publishes natively.',
    icon: '✂️',
    skills: [
      { slug: 'transcriber', name: 'Transcriber', reason: 'Converts speech to text for semantic scene analysis' },
      { slug: 'story-writer', name: 'Story Writer', reason: 'Generates attention-grabbing hooks and captions' },
      { slug: 'chart-generator', name: 'Chart Generator', reason: 'Creates on-screen graphics for stats or quotes' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Times Shorts uploads for peak audience engagement' },
      { slug: 'api-tester', name: 'API Tester', reason: 'Publishes to YouTube/TikTok via official APIs' },
    ],
    searchLink: '/skills?q=video+clipping+shorts+hook+caption+publishing',
  },


  // ── n8n categories ──
  {
    slug: 'ai-chatbot-deployer',
    title: 'Deploy AI Chatbots',
    description: 'Launch domain-specific chatbots that answer questions using your internal documentation and knowledge bases.',
    icon: '🤖',
    skills: [
      { slug: 'support-bot', name: 'Support Bot', reason: 'Handles user queries autonomously' },
      { slug: 'document-processor', name: 'Document Processor', reason: 'Ingests and structures docs for chat' },
      { slug: 'pdf-reader', name: 'PDF Reader', reason: 'Extracts text from PDF knowledge sources' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Manages chatbot deployment and updates' },
      { slug: 'notion-assistant', name: 'Notion Assistant', reason: 'Syncs Notion KB with chat interface' },
    ],
    searchLink: '/skills?q=chatbot+knowledge+base',
  },
  {
    slug: 'ai-rag-connector',
    title: 'RAG Document Chat',
    description: 'Chat interactively with your PDFs, internal wikis, and databases using retrieval-augmented generation.',
    icon: '📚',
    skills: [
      { slug: 'pdf-reader', name: 'PDF Reader', reason: 'Parses and embeds PDF content' },
      { slug: 'web-scraper', name: 'Web Scraper', reason: 'Fetches live web-based knowledge' },
      { slug: 'document-processor', name: 'Document Processor', reason: 'Normalizes formats for RAG indexing' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Analyzes retrieved context relevance' },
      { slug: 'note-taker', name: 'Note Taker', reason: 'Summarizes RAG responses for clarity' },
    ],
    searchLink: '/skills?q=rag+pdf+chat',
  },
  {
    slug: 'ai-summarizer-pro',
    title: 'Auto Summarize Content',
    description: 'Instantly condense emails, meeting transcripts, reports, and web articles into key insights.',
    icon: '✂️',
    skills: [
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Summarizes inbound and outbound emails' },
      { slug: 'note-taker', name: 'Note Taker', reason: 'Distills meeting notes into action items' },
      { slug: 'web-scraper', name: 'Web Scraper', reason: 'Fetches and summarizes web pages' },
      { slug: 'pdf-reader', name: 'PDF Reader', reason: 'Extracts and summarizes document content' },
      { slug: 'report-generator', name: 'Report Generator', reason: 'Creates concise executive summaries' },
    ],
    searchLink: '/skills?q=summarize+email+meeting',
  },
  {
    slug: 'content-creator-studio',
    title: 'AI Content Studio',
    description: 'Generate SEO-optimized blog posts, newsletters, and social media captions in seconds.',
    icon: '✍️',
    skills: [
      { slug: 'social-poster', name: 'Social Poster', reason: 'Drafts platform-optimized social content' },
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Writes engaging newsletter copy' },
      { slug: 'seo-growth', name: 'SEO Growth', reason: 'Adds keyword targeting to drafts' },
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Localizes content across languages' },
      { slug: 'chart-generator', name: 'Chart Generator', reason: 'Creates visual assets for posts' },
    ],
    searchLink: '/skills?q=blog+social+newsletter',
  },
  {
    slug: 'crm-sync-orchestrator',
    title: 'CRM Sync Manager',
    description: 'Automatically sync contacts, update deal stages, and log interactions across HubSpot, Salesforce, and Pipedrive.',
    icon: '🔄',
    skills: [
      { slug: 'crm-manager', name: 'CRM Manager', reason: 'Centralizes multi-CRM operations' },
      { slug: 'lead-generator', name: 'Lead Generator', reason: 'Enriches and imports new leads' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Triggers syncs at optimal times' },
      { slug: 'slack-notifier', name: 'Slack Notifier', reason: 'Alerts teams on CRM changes' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Creates follow-ups from CRM updates' },
    ],
    searchLink: '/skills?q=crm+sync+salesforce',
  },


  // ── n8n categories ──
  {
    slug: 'crypto-trading-orchestrator',
    title: 'Crypto Trading Assistant',
    description: 'Monitors real-time prices, executes trades, tracks portfolio performance, and sends price or event alerts.',
    icon: '📊',
    skills: [
      { slug: 'crypto-tracker', name: 'Crypto Tracker', reason: 'Real-time price and portfolio monitoring' },
      { slug: 'slack-notifier', name: 'Slack Notifier', reason: 'Sends trade confirmations and alerts' },
      { slug: 'chart-generator', name: 'Chart Generator', reason: 'Visualizes price trends and indicators' },
      { slug: 'report-generator', name: 'Report Generator', reason: 'Creates daily/weekly portfolio performance reports' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Automates recurring trade checks and rebalancing' },
    ],
    searchLink: '/skills?q=crypto+trading+alert+portfolio',
  },
  {
    slug: 'devops-automation-hub',
    title: 'DevOps Automation Hub',
    description: 'Automates CI/CD pipelines, monitors deployment health, and securely processes GitHub webhooks.',
    icon: '⚙️',
    skills: [
      { slug: 'github-assistant', name: 'GitHub Assistant', reason: 'Handles pull requests and webhooks' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Triggers builds and deployments on schedule' },
      { slug: 'api-tester', name: 'API Tester', reason: 'Validates post-deployment API endpoints' },
      { slug: 'log-analyzer', name: 'Log Analyzer', reason: 'Monitors deployment logs for errors' },
      { slug: 'security-scanner', name: 'Security Scanner', reason: 'Scans dependencies and containers for vulnerabilities' },
    ],
    searchLink: '/skills?q=devops+ci+cd+github+deployment',
  },
  {
    slug: 'document-extraction-pro',
    title: 'Document Extraction Pro',
    description: 'Extracts structured data like totals, dates, and line items from PDF invoices and receipts.',
    icon: '📄',
    skills: [
      { slug: 'pdf-reader', name: 'PDF Reader', reason: 'Parses text and tables from scanned PDFs' },
      { slug: 'invoice-parser', name: 'Invoice Parser', reason: 'Identifies and extracts key financial fields' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Validates and normalizes extracted numbers/dates' },
      { slug: 'excel-formula', name: 'Excel Formula', reason: 'Generates formulas for reconciliation and reporting' },
      { slug: 'report-generator', name: 'Report Generator', reason: 'Exports parsed data to CSV or Excel reports' },
    ],
    searchLink: '/skills?q=pdf+invoice+receipt+extraction+structured',
  },
  {
    slug: 'document-ops-center',
    title: 'Document Ops Center',
    description: 'Converts, merges, and splits documents while syncing across Google Drive and Notion automatically.',
    icon: '🔄',
    skills: [
      { slug: 'document-processor', name: 'Document Processor', reason: 'Converts formats (PDF, DOCX, Markdown)' },
      { slug: 'notion-assistant', name: 'Notion Assistant', reason: 'Syncs and updates Notion pages with docs' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Triggers batch conversions and merges on schedule' },
      { slug: 'google-drive-integration', name: 'Google Drive Integration', reason: 'Manages uploads, versions, and permissions' },
      { slug: 'report-generator', name: 'Report Generator', reason: 'Logs document ops history and outcomes' },
    ],
    searchLink: '/skills?q=document+convert+merge+notion+drive',
  },
  {
    slug: 'smart-file-manager',
    title: 'Smart File Manager',
    description: 'Organizes, renames, and moves files automatically across cloud storage based on rules and content.',
    icon: '🗂️',
    skills: [
      { slug: 'web-scraper', name: 'Web Scraper', reason: 'Extracts metadata from file names or URLs' },
      { slug: 'pdf-reader', name: 'PDF Reader', reason: 'Reads content to classify and tag files' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Sequences file operations safely and reliably' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Runs cleanup and reorganization on set intervals' },
      { slug: 'slack-notifier', name: 'Slack Notifier', reason: 'Alerts on completed moves or conflicts' },
    ],
    searchLink: '/skills?q=file+organize+rename+cloud+storage',
  },


  // ── n8n categories ──
  {
    slug: 'hr-automation',
    title: 'HR Workflow Automator',
    description: 'Automates job posting, resume screening, and new hire onboarding using integrated tools.',
    icon: '👥',
    skills: [
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Sends templated comms to candidates' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Schedules interviews and onboarding steps' },
      { slug: 'crm-manager', name: 'CRM Manager', reason: 'Syncs candidate data to HRIS/ATS' },
      { slug: 'document-processor', name: 'Document Processor', reason: 'Parses resumes and offer letters' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Books calendars across hiring teams' },
    ],
    searchLink: '/skills?q=hr+automation+onboarding',
  },
  {
    slug: 'wiki-synchronizer',
    title: 'Wiki Auto-Updater',
    description: 'Keeps internal wikis fresh by syncing and transforming docs from Notion or Confluence.',
    icon: '📚',
    skills: [
      { slug: 'notion-assistant', name: 'Notion Assistant', reason: 'Reads and updates Notion knowledge bases' },
      { slug: 'document-processor', name: 'Document Processor', reason: 'Extracts and reformats wiki content' },
      { slug: 'web-scraper', name: 'Web Scraper', reason: 'Pulls public-facing Confluence pages' },
      { slug: 'report-generator', name: 'Report Generator', reason: 'Creates versioned changelogs for docs' },
      { slug: 'slack-notifier', name: 'Slack Notifier', reason: 'Alerts teams when wiki pages update' },
    ],
    searchLink: '/skills?q=wiki+notion+confluence+sync',
  },
  {
    slug: 'invoice-processor',
    title: 'Smart Invoice Handler',
    description: 'Extracts line items, validates totals, reconciles payments, and syncs to QuickBooks or Xero.',
    icon: '🧾',
    skills: [
      { slug: 'invoice-parser', name: 'Invoice Parser', reason: 'Extracts vendor, date, amounts from PDFs' },
      { slug: 'pdf-reader', name: 'PDF Reader', reason: 'Processes scanned and digital invoices' },
      { slug: 'excel-formula', name: 'Excel Formula', reason: 'Validates calculations and tax logic' },
      { slug: 'crm-manager', name: 'CRM Manager', reason: 'Links invoices to client records' },
      { slug: 'report-generator', name: 'Report Generator', reason: 'Exports reconciliation summaries monthly' },
    ],
    searchLink: '/skills?q=invoice+pdf+accounting+reconcile',
  },
  {
    slug: 'it-ops-guardian',
    title: 'IT Ops Guardian',
    description: 'Monitors server metrics, triggers auto-remediation scripts, and logs incidents in Jira.',
    icon: '🖥️',
    skills: [
      { slug: 'api-tester', name: 'API Tester', reason: 'Checks service health endpoints continuously' },
      { slug: 'log-analyzer', name: 'Log Analyzer', reason: 'Detects error patterns in system logs' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Runs periodic health checks and backups' },
      { slug: 'slack-notifier', name: 'Slack Notifier', reason: 'Pages on-call engineers for critical alerts' },
      { slug: 'code-reviewer', name: 'Code Reviewer', reason: 'Audits auto-remediation scripts for safety' },
    ],
    searchLink: '/skills?q=server+monitoring+alert+incident',
  },
  {
    slug: 'lead-gen-orchestrator',
    title: 'Lead Gen Orchestrator',
    description: 'Scrapes target websites, enriches contact data, scores leads, and pushes qualified ones to CRM.',
    icon: '🔍',
    skills: [
      { slug: 'web-scraper', name: 'Web Scraper', reason: 'Extracts prospect emails and firmographics' },
      { slug: 'lead-generator', name: 'Lead Generator', reason: 'Builds targeted lead lists from sources' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Scores leads using engagement and fit signals' },
      { slug: 'crm-manager', name: 'CRM Manager', reason: 'Pushes scored leads with custom fields' },
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Sends personalized outreach drafts' },
    ],
    searchLink: '/skills?q=lead+scraping+enrichment+crm',
  },


  // ── n8n categories ──
  {
    slug: 'lead-nurturing-orchestrator',
    title: 'Lead Nurturing Orchestrator',
    description: 'Automates personalized email sequences and dynamically scores leads based on engagement and behavior.',
    icon: '📧',
    skills: [
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Sends personalized email sequences' },
      { slug: 'lead-generator', name: 'Lead Generator', reason: 'Identifies and enriches new leads' },
      { slug: 'crm-manager', name: 'CRM Manager', reason: 'Syncs and updates lead data in CRM' },
      { slug: 'report-generator', name: 'Report Generator', reason: 'Creates lead scoring performance reports' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Analyzes engagement to refine scoring models' },
    ],
    searchLink: '/skills?q=email+lead+scoring+crm',
  },
  {
    slug: 'marketing-automation-hub',
    title: 'Marketing Automation Hub',
    description: 'Schedules social posts, tracks campaign KPIs across channels, and unifies analytics into actionable dashboards.',
    icon: '📊',
    skills: [
      { slug: 'social-poster', name: 'Social Poster', reason: 'Automates cross-platform social content posting' },
      { slug: 'web-scraper', name: 'Web Scraper', reason: 'Gathers competitor campaign data' },
      { slug: 'chart-generator', name: 'Chart Generator', reason: 'Visualizes campaign performance metrics' },
      { slug: 'report-generator', name: 'Report Generator', reason: 'Compiles multi-channel marketing reports' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Measures ROI and optimizes spend' },
    ],
    searchLink: '/skills?q=social+analytics+campaign+tracking',
  },
  {
    slug: 'market-intelligence-scout',
    title: 'Market Intelligence Scout',
    description: 'Monitors competitor moves, scans industry news, and aggregates real-time market signals for strategic decisions.',
    icon: '🔍',
    skills: [
      { slug: 'web-scraper', name: 'Web Scraper', reason: 'Extracts competitor pricing and feature updates' },
      { slug: 'rss-reader', name: 'RSS Reader', reason: 'Not applicable — use existing slugs only' },
      { slug: 'pdf-reader', name: 'PDF Reader', reason: 'Processes market research whitepapers and reports' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Identifies trends from aggregated market data' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Triggers daily news and alert scans' },
    ],
    searchLink: '/skills?q=competitor+news+market+data',
  },
  {
    slug: 'multimodal-ai-analyzer',
    title: 'Multimodal AI Analyzer',
    description: 'Transcribes audio/video, extracts insights from images and speech, and generates structured summaries.',
    icon: '🎥',
    skills: [
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Not applicable — skip' },
      { slug: 'document-processor', name: 'Document Processor', reason: 'Handles multimodal input like PDFs with embedded media' },
      { slug: 'pdf-reader', name: 'PDF Reader', reason: 'Extracts text and metadata from scanned docs' },
      { slug: 'report-generator', name: 'Report Generator', reason: 'Summarizes transcribed and analyzed multimedia content' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Finds patterns across audio, visual, and textual outputs' },
    ],
    searchLink: '/skills?q=transcription+audio+video+image+analysis',
  },
  {
    slug: 'personal-productivity-coach',
    title: 'Personal Productivity Coach',
    description: 'Automates task prioritization, triages incoming emails, syncs calendar events, and delivers smart reminders.',
    icon: '✅',
    skills: [
      { slug: 'task-planner', name: 'Task Planner', reason: 'Organizes and prioritizes daily tasks' },
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Triages and categorizes incoming messages' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Books meetings and sets intelligent reminders' },
      { slug: 'note-taker', name: 'Note Taker', reason: 'Captures action items from calls and emails' },
      { slug: 'slack-notifier', name: 'Slack Notifier', reason: 'Sends timely alerts and status updates' },
    ],
    searchLink: '/skills?q=task+email+calendar+reminder',
  },


  // ── n8n categories ──
  {
    slug: 'project-management-orchestrator',
    title: 'Project Sync & Report',
    description: 'Syncs tasks across Jira, Linear, and Asana while auto-generating weekly status reports.',
    icon: '📊',
    skills: [
      { slug: 'task-planner', name: 'Task Planner', reason: 'Manages cross-platform task synchronization' },
      { slug: 'report-generator', name: 'Report Generator', reason: 'Creates automated project status reports' },
      { slug: 'notion-assistant', name: 'Notion Assistant', reason: 'Syncs and updates project docs in Notion' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Aligns deadlines and milestones across tools' },
      { slug: 'slack-notifier', name: 'Slack Notifier', reason: 'Posts real-time updates to Slack channels' },
    ],
    searchLink: '/skills?q=task+report+sync',
  },
  {
    slug: 'sales-outreach-orchestrator',
    title: 'Sales Sequence Automator',
    description: 'Automates multi-channel outreach, tracks deal progression, and generates personalized proposals.',
    icon: '📈',
    skills: [
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Sends and follows up on sales emails' },
      { slug: 'crm-manager', name: 'CRM Manager', reason: 'Updates and tracks deal stages in CRM' },
      { slug: 'lead-generator', name: 'Lead Generator', reason: 'Sources and qualifies new prospects' },
      { slug: 'document-processor', name: 'Document Processor', reason: 'Generates and customizes sales proposals' },
      { slug: 'chart-generator', name: 'Chart Generator', reason: 'Visualizes pipeline health and win rates' },
    ],
    searchLink: '/skills?q=sales+outreach+proposal',
  },
  {
    slug: 'secops-incident-orchestrator',
    title: 'Security Alert Responder',
    description: 'Monitors SIEM alerts, auto-triages incidents, triggers response playbooks, and scans for vulnerabilities.',
    icon: '🛡️',
    skills: [
      { slug: 'security-scanner', name: 'Security Scanner', reason: 'Identifies vulnerabilities across assets' },
      { slug: 'log-analyzer', name: 'Log Analyzer', reason: 'Detects anomalies in security logs' },
      { slug: 'incident-responder', name: 'Incident Responder', reason: 'Executes automated containment and alerting' },
      { slug: 'api-tester', name: 'API Tester', reason: 'Validates security posture of internal APIs' },
      { slug: 'slack-notifier', name: 'Slack Notifier', reason: 'Notifies SecOps team on critical alerts' },
    ],
    searchLink: '/skills?q=security+alert+response',
  },
  {
    slug: 'social-media-orchestrator',
    title: 'Social Post & Listen',
    description: 'Schedules cross-platform posts, monitors brand mentions, and sends context-aware auto-replies.',
    icon: '📱',
    skills: [
      { slug: 'social-poster', name: 'Social Poster', reason: 'Publishes and schedules content across platforms' },
      { slug: 'web-scraper', name: 'Web Scraper', reason: 'Collects public mentions and sentiment data' },
      { slug: 'support-bot', name: 'Support Bot', reason: 'Handles common queries with auto-replies' },
      { slug: 'translator-pro', name: 'Translator Pro', reason: 'Translates replies for global audience' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Optimizes post timing based on engagement data' },
    ],
    searchLink: '/skills?q=social+schedule+monitor',
  },
  {
    slug: 'support-orchestrator',
    title: 'Smart Ticket Router',
    description: 'Routes incoming support tickets by intent and urgency, drafts contextual replies, and escalates SLA breaches.',
    icon: '🎫',
    skills: [
      { slug: 'support-bot', name: 'Support Bot', reason: 'Classifies and routes tickets intelligently' },
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Drafts first-response replies from templates' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Flags urgent issues using SLA and sentiment' },
      { slug: 'slack-notifier', name: 'Slack Notifier', reason: 'Alerts teams on high-priority escalations' },
      { slug: 'pdf-reader', name: 'PDF Reader', reason: 'Extracts context from uploaded customer documents' },
    ],
    searchLink: '/skills?q=support+ticket+escalate',
  },


  // ── n8n categories ──
  {
    slug: 'support-chatbot',
    title: 'AI Support Assistant',
    description: 'Automates customer support with real-time answers from your knowledge base and docs.',
    icon: '💬',
    skills: [
      { slug: 'support-bot', name: 'Support Bot', reason: 'Core chatbot for support queries' },
      { slug: 'pdf-reader', name: 'PDF Reader', reason: 'Extracts and indexes KB documents' },
      { slug: 'document-processor', name: 'Document Processor', reason: 'Cleans and structures knowledge base content' },
      { slug: 'slack-notifier', name: 'Slack Notifier', reason: 'Alerts agents on complex unresolved issues' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Books follow-up calls for escalated tickets' },
    ],
    searchLink: '/skills?q=support+chatbot+kb',
  },
  {
    slug: 'ticket-management',
    title: 'Smart Ticket Orchestrator',
    description: 'Auto-creates, triages, and routes support tickets from email, chat, and forms to the right team.',
    icon: '🎫',
    skills: [
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Parses and classifies inbound support emails' },
      { slug: 'web-scraper', name: 'Web Scraper', reason: 'Pulls tickets from public feedback forms' },
      { slug: 'crm-manager', name: 'CRM Manager', reason: 'Syncs and assigns tickets in CRM systems' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Sets SLAs and priority-based deadlines' },
      { slug: 'slack-notifier', name: 'Slack Notifier', reason: 'Notifies teams and updates status in channels' },
    ],
    searchLink: '/skills?q=ticket+management+auto',
  },


  // ── Google 补全驱动 ──
  {
    slug: 'acrobat-ai-assistant',
    title: 'AI Acrobat Assistant',
    description: 'Automate PDF editing, form filling, and document summarization directly inside Adobe Acrobat.',
    icon: '📄',
    skills: [
      { slug: 'pdf-reader', name: 'PDF Reader', reason: 'Extracts text and structure from PDFs' },
      { slug: 'invoice-parser', name: 'Invoice Parser', reason: 'Handles structured data extraction from forms' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Analyzes tabular content in PDF reports' },
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Drafts follow-up emails from PDF notes' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Sets reminders based on deadlines in documents' },
    ],
    searchLink: '/skills?q=ai+acrobat+pdf',
  },
  {
    slug: 'interview-coach-agent',
    title: 'AI Interview Coach',
    description: 'Simulate technical and behavioral interviews with real-time feedback on answers, tone, and body language.',
    icon: '🎤',
    skills: [
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Drafts thank-you emails post-interview' },
      { slug: 'note-taker', name: 'Note Taker', reason: 'Captures key questions and self-reflections' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Schedules practice sessions and prep tasks' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Tracks improvement across interview metrics' },
      { slug: 'report-generator', name: 'Report Generator', reason: 'Creates progress summaries for job seekers' },
    ],
    searchLink: '/skills?q=ai+interview+coach',
  },
  {
    slug: 'ai-jobs-automation',
    title: 'AI Jobs Automation',
    description: 'Scan, filter, and auto-apply to job listings using custom criteria like salary, remote status, and tech stack.',
    icon: '💼',
    skills: [
      { slug: 'web-scraper', name: 'Web Scraper', reason: 'Pulls job listings from company sites and boards' },
      { slug: 'lead-generator', name: 'Lead Generator', reason: 'Identifies high-potential roles matching profile' },
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Personalizes cover letters per application' },
      { slug: 'task-planner', name: 'Task Planner', reason: 'Manages follow-ups and interview timelines' },
      { slug: 'notion-assistant', name: 'Notion Assistant', reason: 'Syncs applications and statuses to Notion DB' },
    ],
    searchLink: '/skills?q=ai+job+automation+apply',
  },
  {
    slug: 'google-ads-optimizer',
    title: 'Google Ads Optimizer',
    description: 'Automatically monitor, A/B test, and adjust Google Ads campaigns based on performance KPIs and budget rules.',
    icon: '📈',
    skills: [
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Analyzes CTR, conversion, and ROAS trends' },
      { slug: 'report-generator', name: 'Report Generator', reason: 'Builds weekly campaign performance summaries' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Triggers bid adjustments during peak hours' },
      { slug: 'slack-notifier', name: 'Slack Notifier', reason: 'Alerts team on anomalies or wins' },
      { slug: 'chart-generator', name: 'Chart Generator', reason: 'Visualizes ad spend vs. conversions over time' },
    ],
    searchLink: '/skills?q=ai+google+ads+optimizer',
  },
  {
    slug: 'interior-design-ai',
    title: 'AI Interior Designer',
    description: 'Generate room layouts, suggest furniture pairings, and simulate lighting/mood using uploaded floor plans or photos.',
    icon: '🛋️',
    skills: [
      { slug: 'web-scraper', name: 'Web Scraper', reason: 'Gathers product specs and pricing from retailers' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Recommends items by style, budget, and dimensions' },
      { slug: 'chart-generator', name: 'Chart Generator', reason: 'Creates mood board color palettes and swatches' },
      { slug: 'note-taker', name: 'Note Taker', reason: 'Logs client preferences and revision history' },
      { slug: 'scheduler', name: 'Scheduler', reason: 'Books vendor consultations and delivery windows' },
    ],
    searchLink: '/skills?q=ai+interior+design+layout',
  },
  {
    slug: 'restaurant-operations-agent',
    title: 'Restaurant AI Agent',
    description: 'Manage daily operations including staff scheduling, inventory alerts, online review responses, and reservation sync.',
    icon: '🍽️',
    skills: [
      { slug: 'scheduler', name: 'Scheduler', reason: 'Assigns shifts based on availability and demand' },
      { slug: 'slack-notifier', name: 'Slack Notifier', reason: 'Pings managers about low stock or no-shows' },
      { slug: 'support-bot', name: 'Support Bot', reason: 'Replies to common reservation and policy queries' },
      { slug: 'email-assistant', name: 'Email Assistant', reason: 'Sends weekly recap emails to owners' },
      { slug: 'data-analysis', name: 'Data Analysis', reason: 'Tracks review sentiment and top complaint themes' },
    ],
    searchLink: '/skills?q=ai+restaurant+operations',
  },
]
